apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation-depl
          image: vighnesh73/moderation
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-serv
spec:
  selector:
    app: moderation
  ports:
    - name: moderation-serv
      protocol: TCP
      port: 7005
      targetPort: 7005