# deployment manages pods in a cluster. Here we are specifying pods for posts
# kubectl apply -f posts.depl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1 # 1 pod
  selector: # select apps matching label app: posts
    matchLabels:
      app: posts
  template:
    metadata: # specifying this pod have label of app: posts
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: vighnesh73/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts-clusterip-srv
      protocol: TCP
      port: 7001
      targetPort: 7001