apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: vighnesh73/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-serv
spec:
  selector:
    app: query
  ports:
    - name: query-serv
      protocol: TCP
      port: 7004
      targetPort: 7004
